// Import global styles
import "./globals.css";

// Import Inter font from Google Fonts using Next.js utility
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// Import ToastContainer for notifications
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Set metadata dynamically or within the component
const metadata = {
  title: "Authentication APP",
  description: "Generated by create next app",
};

// Define the RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Set metadata dynamically */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
